USE Com2900G12
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Venta')
BEGIN
	EXEC('CREATE SCHEMA Venta')
	PRINT 'SCHEMA Venta CREADO'
END
ELSE
	PRINT 'EL SCHEMA Venta YA EXISTE'
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Producto')
BEGIN
	EXEC('CREATE SCHEMA Producto')
	PRINT 'SCHEMA Producto CREADO'
END
ELSE
	PRINT 'EL SCHEMA Producto YA EXISTE'
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Sucursal')
BEGIN
	EXEC('CREATE SCHEMA Sucursal')
	PRINT 'SCHEMA Sucursal CREADO'
END
ELSE
	PRINT 'EL SCHEMA Sucursal YA EXISTE'
GO