USE Com2900G12
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Venta')
BEGIN
	EXEC('CREATE SCHEMA Venta')
END
ELSE
	PRINT 'EL SCHEMA Venta YA EXISTE'
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Producto')
BEGIN
	EXEC('CREATE SCHEMA Producto')
END
ELSE
	PRINT 'EL SCHEMA Producto YA EXISTE'
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='Sucursal')
BEGIN
	EXEC('CREATE SCHEMA Sucursal')
END
ELSE
	PRINT 'EL SCHEMA Sucursal YA EXISTE'
GO